server:
  port: 8080

spring:
  redis:
    hostName: 47.100.63.91
    port: 6379
    password:
  datasource:
    url: "jdbc:mysql://47.100.63.91:3306/architecture?characterEncoding=utf8"
    username: root
    password: "056210"
    driverClassName: "com.mysql.jdbc.Driver"
    initialSize: 2
    maxActive: 20
    minIdle: 0
    maxWait: 60000
    validationQuery: "SELECT 1"
    testOnBorrow: false
    testWhileIdle: true
    poolPreparedStatements: false


